### ISSUE TITLE
Android Signature key

### ISSUE THREAD

**Issue by ithustle** [hiranpeiris/react-native-otp-auto-fill#10]
> Check your console logs: You will get "Android Signature key for SMS body: XXXX" Put that code "XXXX" in backend SMS body like below.

Hey there. Is this key unique per app or per device? 
And is it compatible with firebase auth phone Number?

**Comment by hiranpeiris** [comment]
Just put it to your firebase configuration. It will work.
This is unique to your Keystore file.

**Comment by ithustle** [comment]
@hiranpeiris could you show me where? I just can't figure it out. Btw, it works fine on Android, but on iOS isn't auto fill my inputtext
