### ISSUE TITLE
Doesn't work on Android 

### ISSUE THREAD

**Issue by ErnestMironov** [hiranpeiris/react-native-otp-auto-fill#13]
Invariant Violation: requireNativeComponent: "OtpAutoFillView" was not found in the UIManager.

![image](https://user-images.githubusercontent.com/33957800/173794571-8947580f-0961-4d40-9394-9f7a74eb7089.png)

    "expo": "~45.0.0",
    "expo-asset": "~8.5.0",
    "expo-constants": "~13.1.1",
    "expo-font": "~10.1.0",
    "expo-linking": "~3.1.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-system-ui": "~1.2.0",
    "expo-web-browser": "~10.2.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-otp-auto-fill": "^0.1.17",

**Comment by e4basil** [comment]
facing same issue in expo app
@ErnestMironov have you found any solution ?

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this? Does it work with expo?
