### ISSUE TITLE
Auto fill is not working in the Android Sign APK 

### ISSUE THREAD

**Issue by Satishpethani92** [hiranpeiris/react-native-otp-auto-fill#16]
I have implement this library and test it. it's working well in debug but not getting auto fill in sign apk.

Is there any permission need to add in android manifest file or not ? @hiranpeiris

**Comment by AminDannak** [comment]
> I have implement this library and test it. it's working well in debug but not getting auto fill in sign apk.
> 
> Is there any permission need to add in android manifest file or not ? @hiranpeiris

same problem

**Comment by Satishpethani92** [comment]
@hiranpeiris  Is there any update regarding signed apk ?

**Comment by hiranpeiris** [comment]
@Satishpethani92 
Yes. Just use the following code and get the Android Signature key. Then put it in your SMS body.

// This is only needed once to get the Android Signature key for SMS body
  const handleOnAndroidSignature = ({
    nativeEvent: { code },
  }: NativeSyntheticEvent<{ code: string }>) => {
     Alert.alert('Android Signature Key for SMS body:', code);
  };
  
Note: Remove this after you read the Android Signature key.

**Comment by muzammil-kt** [comment]
Any update?

**Comment by Satishpethani92** [comment]
> > I have implement this library and test it. it's working well in debug but not getting auto fill in sign apk.
> > Is there any permission need to add in android manifest file or not ? @hiranpeiris
> 
> same problem

Now it's working Thank you!
