### ISSUE TITLE
not running on iOS

### ISSUE THREAD

**Issue by preetikat240486** [hiranpeiris/react-native-otp-auto-fill#8]
Invariant Violation: requireNativeComponent: "OtpAutoFillView" was not found in the UIManager.

<View style={styles.container}>
        <OtpAutoFillViewManager
          onComplete={handleComplete}
          onAndroidSignature={handleOnAndroidSignature}
          style={styles.box}
          length={6} // Define the length of OTP code. This is a must.
        />
      </View>

**Comment by ithustle** [comment]
Hey @preetikat240486. Did you run `pod install` ?

**Comment by hiranpeiris** [comment]
@preetikat240486 You need to run the pod install.
Let me know if you still get this error.
